FROM ubuntu:14.04

#
# Basic structure of that Docker container:
# /iguana/
#        /config.xml    IGUANA xml configuration file
#        /jars          Contains neccessary jar-files required by the Benchmark
#        /results/      Contains resulting data generated by the Benchmark
#        /start.sh      To start the benchmark (autostart)
#

MAINTAINER Konrad Abicht <abicht@informatik.uni-leipzig.de>

# Let the conatiner know that there is no tty
ENV DEBIAN_FRONTEND noninteractive

# update package index
RUN apt-get update

# install some java
RUN apt-get install -y openjdk-7-jre

# iguana is the main folder which contains all relevant files and folders
# later on, you will be able to modify its content, for instance set the
# results folder. in that way have the maximum freedom as an user
RUN mkdir /iguana

# add config.xml and queries.txt
ADD config.xml /iguana/config.xml
ADD queries.txt /iguana/queries.txt

# /iguana/jars will contain all required jar files
RUN mkdir /iguana/jars
# put Jars into the Docker
ADD iguana-jars /iguana/jars

# results folder will contain resulting data (e.g. diagrams, stats, ...)
RUN mkdir /iguana/results

# add start script to execute the benchmark
ADD start.sh /iguana/start.sh

WORKDIR /iguana

CMD ["/bin/bash", "/iguana/start.sh"]
